# Site settings
title: Human-Computer Interaction
tagline: COSE432
description: 2024 HCI course website for undergraduates at Korea University
author: Dr. Gerard Jounghyun Kim
baseurl: '/hci'
url: 'https://ku-dxplab.github.io'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.9.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Dr. Gerard Jounghyun Kim:
    - 'https://scholar.google.com/citations?user=7UCco8IAAAAJ&hl=en'
  DXP Lab:
    - 'https://dxp.korea.ac.kr'
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true
